server:
  error:
    include-stacktrace: never

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO