server:
  port: ${PORT:5000}

base-url: /api

spring:
  application:
    name: to-do-my-list

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true